### ISSUE TITLE
[Mostly solved; postponed] Make the code with type-level magic more readable and simpler

### ISSUE THREAD

**Issue by Mikolaj** [Mikolaj/horde-ad#13]
Here are the samples from the library code that only library maintainers are supposed to write:

https://github.com/Mikolaj/horde-ad/blob/93f1d067f7634c6505bcf4f2dc8614c8a302a5f8/src/HordeAd/Core/Delta.hs#L452-L454

https://github.com/Mikolaj/horde-ad/blob/93f1d067f7634c6505bcf4f2dc8614c8a302a5f8/src/HordeAd/Core/Delta.hs#L464-L479

And here is the code that, potentially, library users may want to write, extend, override:

https://github.com/Mikolaj/horde-ad/blob/93f1d067f7634c6505bcf4f2dc8614c8a302a5f8/src/HordeAd/Core/DualNumber.hs#L4-L5

https://github.com/Mikolaj/horde-ad/blob/93f1d067f7634c6505bcf4f2dc8614c8a302a5f8/src/HordeAd/Core/DualNumber.hs#L306-L316

Could any of this be simplified? Can the GHC plugins be avoided, could this be ported to GHC 8.10, can the auxiliary functions be avoided and the code written inline in the case expression instead?

Here's the library and the types underneath: https://hackage.haskell.org/package/orthotope-0.1.2.0/docs/Data-Array-Shaped.html

**Comment by Mikolaj** [comment]
Related design questions below (to be answered via experiments, but these can be informed in advance by experience with type level programming in other projects).

* Currently we have a strange mix: totally untyped DeltaX, de-facto rank-typed Delta0, Delta1 and Delta 2, fully typed (shape == rank and size) DeltaS. However, debugging sizes turns out to be a pain, so we need shapes also for matrices and vectors. So perhaps use DeltaS instead of matrices? Or should we rather make matrices shaped? 
* Or perhaps place all objective function parameters (including matrices and vectors) in the vector of DeltaS tensors, move them around as shaped and convert them to matrices just before matrix multiplication and quickly convert, e.g., the resulting vector again into a shaped tensor?
* If we stick to only rank-typed matrices and vectors, should we replace Delta0 (unlikely, would cause 100 times slowdown), Delta1, Delta2 with (Delta (n::Nat)), e.g., using the rank-typed tensors from orthotope and so adding a third kind of sensors into the mix? Or remove the fully untyped DeltaX at that point?

**Comment by goldfirere** [comment]
My intuition is that we're always going to need the type-checker plugins -- unless we abandon static shape checking.

The last code block in the ticket looks like it will be hard to fix, especially given the way orthotope works.

There might be further simplification possible, but it's really hard to know without a decent amount of time understanding the implementation better. My sense is that we should try to fix other problems first and then return.

**Comment by Mikolaj** [comment]
The last point in https://github.com/Mikolaj/horde-ad/issues/13#issuecomment-1058544538 is from Simon and I agree we don't yet have enough experience using the library (nor even any stable API) and enough understanding of the design space to predict the relative consequences of such choices. Clearly what we have now is a zoo of approaches, but this makes it easier to experiment, though looks bad in a paper and would be a nightmare to support in the long run.

**Comment by Mikolaj** [comment]
With the move to the `Tensor` class https://github.com/Mikolaj/horde-ad/blob/a361d2694df4f181ee6256ac8d0748e66d5896d4/simplified/HordeAd/Core/TensorClass.hs#L52-L204 we have a somehow different design space, so let me close this and we'd open more relevant issues as they arise.
