### ISSUE TITLE
Nest HasDual instances, e.g.,  `Tensor a`, where `a` can be any HasDual instance

### ISSUE THREAD

**Issue by Mikolaj** [Mikolaj/horde-ad#17]
This issue is hard, because, unlike in the paper, we also have polymorphism over the underlying scalar, over rank and over gradient/derivative, so the nesting can't be expressed by the same type parameterization (we've been there, it's a mess, see #10). OTOH, adding yet another parameter to Delta and DualNumber is much more notational noise. Perhaps there is yet another solution?

This feature makes it possible to implement https://hackage.haskell.org/package/orthotope-0.1.2.0/docs/Data-Array-Shaped.html#v:unravel and similar operations that are useful in ML. This is in contrast and in addition to operations that don't require nested tensors, such as `rerank` and (probably not as commonly used) generalization of matrix operations, such as multiplication of cubes (different from element-wise multiplication of every matrix slice along a chosen dimension. 

For the last category the following keywords and links may have further info (or perhaps some of these are of the former categories?); 
groupMatMul? 
batchMatMul? 
https://numpy.org/doc/stable/reference/generated/numpy.einsum.html 
https://github.com/arogozhnikov/einops

Yet another advantage of nested tensors is that I had the impression that sometimes a vector of vectors may be cheaper than an array, in particular in indexing-like operations, where `eval` of matrix delta expressions requires evaluation at the matrix level `eval2` per matrix row, while analogous `eval` of a vector of vectors evaluates the same at the `eval1` level and so not allocating matrices. OTOH, matrix multiplication is always much faster than its simulation as a sequence of vector dot products. Also, this would need to be a boxed vector of unboxed vectors, which is inefficient in itself compared to fully unboxed matrix. 

Similarly rank `n + k` orthotope tensor is fully unboxed, while the same tensor with `n` nested inside `k` may or may not be unboxed (to investigate, but I don't see how it could be). OTOH, often the outer nesting ranks are not wide and they correspond to physical concepts, e.g., on which GPU unit the slice is computed, so the boxing is cheap and there's no risk of re-index/swap dimensions that switches the `n` and `k`, making the unboxed outer tensor 10^6 wide.

**Comment by goldfirere** [comment]
This sounds like an area I could be helpful, but I don't understand the problem well enough yet. Can you give a few short examples of how you'd like this to work? Or maybe we can make this the subject of a future call.

**Comment by Mikolaj** [comment]
I have no idea how this could possibly work. :D

I'd first remove the overlapping instances from #16, which may require changes to the classes and types we have (BTW, could you perhaps rebase the PR so that GHC 8.10.7 CI shows the overlapping instances and I so can easily see them?). Then I'd tackle #15, which may change the classes again, because I have a lot of trouble making it work (see https://github.com/Mikolaj/horde-ad/tree/both-gradient-derivative; I would love to get some advice there). Then indeed it would be great to try and fit the nested tensors.

In short, currently we have

```
transpose2 :: Numeric r => DualNumber (Matrix r) -> DualNumber (Matrix r)
transpose2 (D u u') = D (HM.tr' u) (Transpose2 u')
```

the nested tensors would enable something like

```
mapTranspose2 :: Numeric r => DualNumber (Vector (Matrix r)) -> DualNumber (Vector (Matrix r))
mapTranspose2 (D u u') = ???
```

that transposes every matrix on a vector. I guess, for simplicity, the nesting would be limited to tensors, so these would be (OT.Array (OT.Array r)), where the outer array has rank 1, the inner rank 2. Examples of more general operations are in the main description of this ticket. Please feel free to ask question and discuss, I have no idea how to solve this, but I have some understanding of the problem itself.

Note that the above is much harder to pull out than

```
mapTranspose2 :: Numeric r => Vector (DualNumber (Matrix r)) -> Vector (DualNumber (Matrix r))
mapTranspose2 (D u u') = ???
```

We may end up using this formulation, but experiments show that in many practical cases working with containers of dual numbers instead of dual numbers representing containers degrades performance orders of magnitude. (This is tested only with sum of nested ranks <= 2, because we don't have neural net experiments with  more than arrays, for now.)

**Comment by goldfirere** [comment]
I've taken a cursory look at this. It would seem to me that `mapTranspose2` would need the `HasRanks` class to be extended, no? Or maybe there's an operation there that already does the trick? I don't know enough of the landscape to answer. This is really something we should discuss on a call.

**Comment by Mikolaj** [comment]
Given your kind interest, I've updated the code snippets above to the current state of the library, which seems to stabilize in its new form, for the moment.

Yes, `HasRanks` would need to be extended, both the type families and operations. Let me repeat: I have no clue how to do that, but I'd gladly chat.

**Comment by Mikolaj** [comment]
And/or `IsDual` would need to be extended. Surely `Delta*` as well.

**Comment by goldfirere** [comment]
Aha. I now understand the task better. I somehow thought you wanted to work within the current confines of these classes. I will take another spin in due course.
