### ISSUE TITLE
Rename dM_MD2 and related functions

### ISSUE THREAD

**Issue by awf** [Mikolaj/horde-ad#21]
dM_MD2 is not as intuitive a name as some of the others

**Comment by Mikolaj** [comment]
It seems, the old implementation with hand-written Delta-expressions for matrices is not coming back. Therefore, the old code with the cryptic names won't be restored and we are now going to permanently work with the "simplified" codebase that, while an order of magnitude more complex that the previous one, is also more general and so the names are more readable. Closing.
