### ISSUE TITLE
Rename scalar to constant

### ISSUE THREAD

**Issue by tomjaguarpaw** [Mikolaj/horde-ad#29]
Shouldn't `scalar` be called `constant`? I doesn't seem to be restricted to scalars and it's for creating constants!

https://github.com/Mikolaj/horde-ad/blob/95fba8f42f5063d9599606a3308e7c5275d5e81c/src/HordeAd/Core/DualNumber.hs#L128-L129

**Comment by Mikolaj** [comment]
I agree the ambiguity is awful and we avoid the clash with constant from

https://hackage.haskell.org/package/orthotope-0.1.2.0/docs/Data-Array-ShapedS.html#v:constant

by calling our constant dual number functions konst*, after package hmatrix, so your proposal makes sense. Another option is `fromPrimal`.
