### ISSUE TITLE
cabal test takes ages to complete and uses only 2 cores

### ISSUE THREAD

**Issue by sfindeisen** [Mikolaj/horde-ad#40]
When running `cabal test` on my `8x Intel(R) Core(TM) i7-7700HQ CPU @ 2.80GHz` with `32 GB RAM` I had to cancel it after some 18 minutes:

```
$ cabal test 
Build profile: -w ghc-9.2.2 -O1
In order, the following will be built (use -v for more details):
 - horde-ad-0.1.0.0 (lib) (configuration changed)
 - horde-ad-0.1.0.0 (lib:testLibrary) (configuration changed)
 - horde-ad-0.1.0.0 (test:shortTestForCI) (configuration changed)
 - horde-ad-0.1.0.0 (test:extremelyLongTest) (dependency rebuilt)
Configuring library for horde-ad-0.1.0.0..
Preprocessing library for horde-ad-0.1.0.0..
Building library for horde-ad-0.1.0.0..
Configuring library 'testLibrary' for horde-ad-0.1.0.0..
Preprocessing library 'testLibrary' for horde-ad-0.1.0.0..
Building library 'testLibrary' for horde-ad-0.1.0.0..
Configuring test suite 'shortTestForCI' for horde-ad-0.1.0.0..
Preprocessing test suite 'extremelyLongTest' for horde-ad-0.1.0.0..
Building test suite 'extremelyLongTest' for horde-ad-0.1.0.0..
[...]
Preprocessing test suite 'shortTestForCI' for horde-ad-0.1.0.0..
Building test suite 'shortTestForCI' for horde-ad-0.1.0.0..
Running 1 test suites...
Test suite shortTestForCI: RUNNING...
Running 1 test suites...
Test suite extremelyLongTest: RUNNING...
^C
```

More importantly, this test suite appears to utilize just 2 CPU cores. It turns my laptop into a small cooker, though: `+96 °C` aka `+204.8 °F` (CPU temp.).

**Comment by Mikolaj** [comment]
Right. I think the 2 cores come from running two test suites. I think there are ways to parallelize each of the suites. Anyway, if your computer is not up to the task, please disregard the extremelyLongTest.

**Comment by Mikolaj** [comment]
BTW, perhaps cleaning the fan might do the trick?

The tests really are computation-intensive: the computer learns to recognize and then recognizes man thousands of digits from pictures, using many different methods. With a short test you wouldn't be able to tell if the neural network learned anything.
