### ISSUE TITLE
In approx tests, HUnitFailure is not caught and not pretty-printed

### ISSUE THREAD

**Issue by Mikolaj** [Mikolaj/horde-ad#60]
I'm getting

```
1 epoch, 1 batch: Validation error: 49.41%
FAIL
      Exception: HUnitFailure (Just (SrcLoc {srcLocPackage = "horde-ad-0.1.0.0-inplace-testLibrary", srcLocModule = "TestCommonEqEpsilon", srcLocFile = "test/common/TestCommonEqEpsilon.hs", srcLocStartLine = 104, srcLocStartCol = 5, srcLocEndLine = 104, srcLocEndCol = 16})) (Reason "expected: 0.0\n but got: 0.49411762\n (maximum margin of error: 1.0e-6)")
      Use -p '/Speech RNN/&&/1 epoch, 1 batch: 1 1 128 10 8 82562 0.2/' to rerun this test only.
```

Instead of something more like

```
1 epoch, all batches: Epochs to run/max batches per epoch: 1/9999
FAIL (44.77s)
      test/common/TestSpeechRNN.hs:334:
      expected: 26.52266
       but got: 39.848167
      Use -p '/Speech RNN/&&/Load and sanity check training speech files/' to rerun this test only.
```

**Comment by sfindeisen** [comment]
This is coming from here: https://github.com/Mikolaj/horde-ad/blob/master/test/common/TestCommonEqEpsilon.hs#L51 . But it's not an exception, it's an `Assertion = IO ()`, which prints this message once evaluated. Therefore I can see no way to catch this exception (in our code).

**Comment by Mikolaj** [comment]
Therefore I can see no way to catch this exception (in our code).

Too bad. Let's catch it not in our code. In HUnit-approx code perhaps?

**Comment by sfindeisen** [comment]
Ok I am actually confused --- see [this draft PR](https://github.com/Mikolaj/horde-ad/pull/63). If nothing is thrown, where is `DEBUG-XXX-3` in the output? If `HUnitFailure` is thrown, why is it not being catched?

**Comment by sfindeisen** [comment]
I am currently testing with:

```
cabal test shortTestForCI --enable-optimization --test-options='-p "/2 artificial 5 4 3 2 1: 5 4 3 2 2393 1.0/"'
```

**Comment by sfindeisen** [comment]
The funny thing is, this error message:

```
FAIL
      Exception: HUnitFailure (Just (SrcLoc {srcLocPackage = "horde-ad-0.1.0.0-inplace-testLibrary", srcLocModule = "TestCommonEqEpsilon", srcLocFile = "test/common/TestCommonEqEpsilon.hs", srcLocStartLine = 113, srcLocStartCol = 5, srcLocEndLine = 113, srcLocEndCol = 16})) (Reason "expected: 0.8991\n but got: 0.7424999999999999\n (maximum margin of error: 1.0e-6)")

1 out of 1 tests failed (13.43s)
```

is red when running in my repo dir (https://github.com/sfindeisen/horde-ad), but default color when running in this repo dir. Same user, no tweaks to the shell after login...

**Comment by Mikolaj** [comment]
> I am currently testing with:
> 
> ```
> cabal test shortTestForCI --enable-optimization --test-options='-p "/2 artificial 5 4 3 2 1: 5 4 3 2 2393 1.0/"'
> ```

On your branch I am getting

```
2 artificial 5 4 3 2 1: Validation error: 89.91%
DEBUG-XXX-0
DEBUG-XXX-1
DEBUG-XXX-2
DEBUG-XXX-3
OK (22.87s)

All 1 tests passed (22.87s)
```

which does not include any error message, in red or otherwise. Is this because of numerical instability? Could you tweak the expected test result on your branch so that we are getting the same behaviour?

**Comment by sfindeisen** [comment]
I suggest you test with another testcase, one that fails for you.

**Comment by Mikolaj** [comment]
None fail for me. I thought none fail for you, too, after the tweaks you made recently?

**Comment by Mikolaj** [comment]
I've found the test and changed the expected results and now I'm getting 

```
2 artificial 5 4 3 2 1: Validation error: 89.91%
DEBUG-XXX-0
DEBUG-XXX-1
DEBUG-XXX-2
FAIL
      Exception: HUnitFailure (Just (SrcLoc {srcLocPackage = "horde-ad-0.1.0.0-inplace-testLibrary", srcLocModule = "TestCommonEqEpsilon", srcLocFile = "test/common/TestCommonEqEpsilon.hs", srcLocStartLine = 112, srcLocStartCol = 5, srcLocEndLine = 112, srcLocEndCol = 35})) (Reason "expected: 0.1991\n but got: 0.8991\n (maximum margin of error: 1.0e-6)")

1 out of 1 tests failed (452.13s)
Test suite shortTestForCI: FAIL
Test suite logged to:
/home/mikolaj/r/horde-ad/dist-newstyle/build/x86_64-linux/ghc-9.0.2/horde-ad-0.1.0.0/t/shortTestForCI/test/horde-ad-0.1.0.0-shortTestForCI.log
0 of 1 test suites (0 of 1 test cases) passed.
Error: cabal: Tests failed for test:shortTestForCI from horde-ad-0.1.0.0.
```

**Comment by Mikolaj** [comment]
The error message is red. I'm running from your branch, checkout in my (main) repo.

**Comment by Mikolaj** [comment]
BTW, the above was cabal mistakenly running unoptimized test (that I also compiled). After `cabal clean` and compiling only the optimized one, I get similar results and also in red, but faster:

```
2 artificial 5 4 3 2 1: Validation error: 89.91%
DEBUG-XXX-0
DEBUG-XXX-1
DEBUG-XXX-2
FAIL
      Exception: HUnitFailure (Just (SrcLoc {srcLocPackage = "horde-ad-0.1.0.0-inplace-testLibrary", srcLocModule = "TestCommonEqEpsilon", srcLocFile = "test/common/TestCommonEqEpsilon.hs", srcLocStartLine = 112, srcLocStartCol = 5, srcLocEndLine = 112, srcLocEndCol = 35})) (Reason "expected: 0.1991\n but got: 0.8991\n (maximum margin of error: 1.0e-6)")

1 out of 1 tests failed (26.14s)
```

BTW, you CPU seem obscenely fast. Mine is AMD Ryzen 3 3100, around 4GHz in such workloads.

**Comment by Mikolaj** [comment]
Off topic: in a PR I'm working on tests run in 415.98s and sequentially in 739.92s (4 cores, 8 threads). Totally worth it. I guess the pattern of access to resources changed (vs. last time when the difference was 10% or 20% tops). Resource being just RAM and caches or perhaps FFI to C/Fortran libs blocks something as well.

**Comment by sfindeisen** [comment]
> Off topic: in a PR I'm working on tests run in 415.98s and sequentially in 739.92s (4 cores, 8 threads). Totally worth it. I guess the pattern of access to resources changed (vs. last time when the difference was 10% or 20% tops). Resource being just RAM and caches or perhaps FFI to C/Fortran libs blocks something as well.

It would be interesting to understand why. :)

Which PR is that? 62?

**Comment by sfindeisen** [comment]
> BTW, you CPU seem obscenely fast. Mine is AMD Ryzen 3 3100, around 4GHz in such workloads. [Edit: or it may be my ancient Ubuntu, kernel and libs. GHC is 9.0.2.]

Hm, weird. I have `Intel(R) Core(TM) i7-7700HQ CPU @ 2.80GHz` on a 5 years old laptop machine. I do not think my 8 cores matter at all because `-f test_seq` does not make any real difference (is actually slightly faster).

**Comment by Mikolaj** [comment]
> Which PR is that? 62?

Yes. I've just pushed the version with these figures (415.98s vs 739.92s). And I think current master branch has the 10% or 20% difference. I now remember, I've just increased how much memory is available to GC from the start, in .cabal file. Without the extra GC memory, it's 485.59s vs 612.29s (more memory for GC actually harms sequential mode, but it helps small benchmarks and make them less fragile). Also, the tests now take more time in general, without increased data size, so perhaps there is more local CPU work to do, not just waiting for RAM. Other than that, frankly, I have idea. Just as I can't quite account for the 10x increased allocation vs master branch in small benchmarks (runtime is only twice worse now and so is explainable enough).

> i7 .. on a 5 years old laptop machine

This is preposterous. OTOH, mine is only i3 tier, but it's from 2 years ago. OYAH, Moore's law is dead.

**Comment by sfindeisen** [comment]
Ok I managed to catch that exception:

```
$ cabal test shortTestForCI --enable-optimization --test-options='-p "/2 artificial 5 4 3 2 1: 5 4 3 2 2393 1.0/"'
[...]
DEBUG-XXX-0
DEBUG-XXX-1
DEBUG-XXX-2
Hello from exceptionHandler! We got HUnitFailure: HUnitFailure (Just (SrcLoc {srcLocPackage = "horde-ad-0.1.0.0-inplace-testLibrary", srcLocModule = "TestCommonEqEpsilon", srcLocFile = "test/common/TestCommonEqEpsilon.hs", srcLocStartLine = 114, srcLocStartCol = 5, srcLocEndLine = 114, srcLocEndCol = 16})) (Reason "expected: 0.8991\n but got: 0.7424999999999999\n (maximum margin of error: 1.0e-6)")
FAIL
      Exception: HUnitFailure (Just (SrcLoc {srcLocPackage = "horde-ad-0.1.0.0-inplace-testLibrary", srcLocModule = "TestCommonEqEpsilon", srcLocFile = "test/common/TestCommonEqEpsilon.hs", srcLocStartLine = 114, srcLocStartCol = 5, srcLocEndLine = 114, srcLocEndCol = 16})) (Reason "expected: 0.8991\n but got: 0.7424999999999999\n (maximum margin of error: 1.0e-6)")

1 out of 1 tests failed (13.78s)

Test suite shortTestForCI: FAIL
[...]
```

It's not `HUnitFailure`, but it's `SomeException`.

**Comment by sfindeisen** [comment]
WHY, oh why can't we have checked exceptions (like in Java), well documented exception type hierarchy, exception catching and throwing using first-class language constructs rather than a bunch of custom GHC-specific (?) functions hidden in some packages out there, working in different ways depending on the IO monad context?

**Comment by Mikolaj** [comment]
This is real power. If you are not ready for it, here are the basics and they suffice for almost everything:

https://downloads.haskell.org/ghc/latest/docs/libraries/base-4.17.0.0/Control-Exception.html

**Comment by Mikolaj** [comment]
> I have to throw something (in this case: rethrow, i.e. throwIO) otherwise all the testcase output gets lost (including putStrLn from the exception handler).

With the `throwIO` commented out I'm getting

```
2 artificial 5 4 3 2 1: Validation error: 89.91%
DEBUG-XXX-0
DEBUG-XXX-1
DEBUG-XXX-2
Hello from exceptionHandler! We got HUnitFailure: HUnitFailure (Just (SrcLoc {srcLocPackage = "horde-ad-0.1.0.0-inplace-testLibrary", srcLocModule = "TestCommonEqEpsilon", srcLocFile = "test/common/TestCommonEqEpsilon.hs", srcLocStartLine = 115, srcLocStartCol = 5, srcLocEndLine = 115, srcLocEndCol = 35})) (Reason "expected: 0.1991\n but got: 0.8991\n (maximum margin of error: 1.0e-6)")
DEBUG-XXX-3
OK (23.91s)

All 1 tests passed (23.91s)
Test suite shortTestForCI: PASS
Test suite logged to:
/home/mikolaj/r/horde-ad/dist-newstyle/build/x86_64-linux/ghc-9.0.2/horde-ad-0.1.0.0/t/shortTestForCI/test/horde-ad-0.1.0.0-shortTestForCI.log
1 of 1 test suites (1 of 1 test cases) passed.
```

Perhaps you removed `test-show-details: direct` from your `cabal.project.local`? You can add it on commandline as `--test-show-details=direct`.

**Comment by sfindeisen** [comment]
Just discovered: https://github.com/UnkindPartition/tasty/issues/327

**Comment by sfindeisen** [comment]
It should work now, please check.

**Comment by Mikolaj** [comment]
> Yes. I've just pushed the version with these figures (415.98s vs 739.92s). And I think current master branch has the 10% or 20% difference. I now remember, I've just increased how much memory is available to GC from the start, in .cabal file. Without the extra GC memory, it's 485.59s vs 612.29s (more memory for GC actually harms sequential mode, but it helps small benchmarks and make them less fragile). 

Actually, `-with-rtsopts` overwrites earlier occurrences, so these figures may be wrong, though the trend they imply seems to hold. Currently on #62 (in a version not yet pushed), with somewhat optimized code, shortened tests and lots of RAM for GC I have 229.33s (par) vs 640.25s (seq) and with default GC settings I have 407.14s vs 576.41s.
